- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: flake8
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
  sha: v2.1.1
  hooks:
  - id: pydocstyle
    exclude: blog/migrations

- repo: git://github.com/pre-commit/mirrors-pylint.git
  rev: v1.9.1
  hooks:
  - id: pylint
    args:
    - --msg-template={path}:L {line:3d}:({symbol}) {msg} (C {column:2d}), ::{msg_id}
    - --output-format=colorized
    - |-
        --init-hook=
        import os, platform, shutil, sys;
        sys.path.insert(
            0,
            "".join([os.getenv("HOME"), "/virtualenv/python", platform.python_version(),
            "/lib/python", ".".join(platform.python_version_tuple()[:2]), "/site-packages"])
            if os.getenv("TRAVIS") else
            "".join([os.getenv("HOME"), "/.virtualenv/django_girls/lib/python", platform.python_version(), "/site-packages"])
        )  # inject virtualenv packages into a module search path; could also go for pylint-venv hook
    - --load-plugins=pylint_django
    - --good-names=pk,urlpatterns
    exclude: blog/migrations/
