-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    sha: master
    hooks:
    -   id: pydocstyle
